#!/usr/bin/env python

import sys

from Centauri6dof import Centauri6dof
from rqt_gui.main import Main

plugin = 'rqt_centauri6dof.centauri6dof.Centauri6dof'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))